PANDAS

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('articles.csv')

In [3]:
df.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

In [4]:
%time
print(df['prod_name'].str.upper().str.replace('S','R').str.lower())
print(df['product_type_name'].str.upper().str.replace('S','R').str.lower())
print(df['product_group_name'].str.upper().str.replace('S','R').str.lower())

CPU times: user 2 µs, sys: 2 µs, total: 4 µs
Wall time: 8.11 µs
0                      rtrap top
1                      rtrap top
2                  rtrap top (1)
3              op t-rhirt (idro)
4              op t-rhirt (idro)
                   ...
105537    5pk regular placement1
105538         rport malaga tank
105539           cartwheel drerr
105540          claire hair claw
105541              lounge drerr
Name: prod_name, Length: 105542, dtype: object
0          vert top
1          vert top
2          vert top
3               bra
4               bra
            ...
105537        rockr
105538     vert top
105539        drerr
105540    hair clip
105541        drerr
Name: product_type_name, Length: 105542, dtype: object
0         garment upper body
1         garment upper body
2         garment upper body
3                  underwear
4                  underwear
                 ...
105537        rockr & tightr
105538    garment upper body
105539     garment full body
105540           accerrorier
105541     garment full body
Name: product_group_name, Length: 105542, dtype: object

In [5]:
from pyspark.sql import SparkSession

In [6]:
spark = SparkSession.builder.appName('PySpark').getOrCreate()

22/03/30 19:00:45 WARN Utils: Your hostname, BTCCHL0018 resolves to a loopback address: 127.0.1.1; using 192.168.0.233 instead (on interface wlp44s0)
22/03/30 19:00:45 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/stephenraj/spark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/03/30 19:00:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/03/30 19:00:47 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

In [7]:
df = spark.read.option('header','true').csv('articles.csv')

In [8]:
%time

from pyspark.sql.functions import translate,upper,lower
df.withColumn('prod_name', lower(translate(upper('prod_name'), 'S', 'R'))).select('prod_name').show()
df.withColumn('product_type_name', lower(translate(upper('product_type_name'), 'S', 'R'))).select('product_type_name').show()
df.withColumn('product_group_name', lower(translate(upper('product_group_name'), 'S', 'R'))).select('product_group_name').show()

#df.show()

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 6.68 µs
+--------------------+
|           prod_name|
+--------------------+
|           rtrap top|
|           rtrap top|
|       rtrap top (1)|
|   op t-rhirt (idro)|
|   op t-rhirt (idro)|
|   op t-rhirt (idro)|
| 20 den 1p rtockingr|
| 20 den 1p rtockingr|
|rhape up 30 den 1...|
|rupport 40 den 1p...|
|   200 den 1p tightr|
|      rweatrhirt  oc|
|      rweatrhirt  oc|
|   alice bandeau 2-p|
|   alice bandeau 2-p|
|   frugan longrleeve|
|jerry jogger bottomr|
|jerry jogger bottomr|
|jerry jogger bottomr|
|jerry jogger bottomr|
+--------------------+
only showing top 20 rows

+-----------------+
|product_type_name|
+-----------------+
|         vert top|
|         vert top|
|         vert top|
|              bra|
|              bra|
|              bra|
| underwear tightr|
|            rockr|
|  leggingr/tightr|
| underwear tightr|
| underwear tightr|
|          rweater|
|          rweater|
|              bra|
|              bra|
|              top|
|         trourerr|
|         trourerr|
|         trourerr|
|         trourerr|
+-----------------+
only showing top 20 rows

+------------------+
|product_group_name|
+------------------+
|garment upper body|
|garment upper body|
|garment upper body|
|         underwear|
|         underwear|
|         underwear|
|    rockr & tightr|
|    rockr & tightr|
|garment lower body|
|    rockr & tightr|
|    rockr & tightr|
|garment upper body|
|garment upper body|
|         underwear|
|         underwear|
|garment upper body|
|garment lower body|
|garment lower body|
|garment lower body|
|garment lower body|
+------------------+
only showing top 20 rows